# run_name: 2022-11-29_20-53-04
# model_path: outputs/2022-11-29_20-53-04/saved_models/epoch=0-val_mae=0.027694.ckpt
# refactor by saf
run_path: /dtu/blackhole/19/s176453/diffusion_for_speech/model_checkpoints/pretrained
checkpoint_name: checkpoint_pl.ckpt
device: gpu
audio_path: /dtu/blackhole/19/s176453/diffusion_for_speech/synthesized_audio/experiment1/default
n_audiofiles: 1
#lang: en
