transformer: diffspeak.datasets.utils.Spectrogrammer
path: ./data/tj/raw/LJSpeech-1.1/
subset_frac: 0.01
sample_rate: 22050
n_mels: 80
n_fft: 1024
hop_samples: 256
crop_mel_frames: 62 # Maybe not correct?
