class_name: diffspeak.models.model
params:
  residual_layers: 30
  residual_channels: 64
  dilation_cycle_length: 10
  unconditional: False
  noise_schedule: # Has to be something custom np.linspace(1e-4, 0.05, 50).tolist(),
  inference_noise_schedule: [0.0001, 0.001, 0.01, 0.05, 0.2, 0.5]
  audio_len: 110250