defaults:
  - _self_
  - callbacks: callbacks
  - private: default
  - datamodule: tjspeech_cond_pretrained
  - inference: pretrained
  - logging: wandb
  - loss: L1loss
  - metric: mae
  - model: diffwave_base_pretrained
  - optimizer: adam
  - scheduler: linearwithwarmup
  - trainer: default_trainer
  - training: lj_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: Pretrained_run
  logs_folder_name: logs
  workspace: dmiai-mh
  project_name: DL2022
  device: cpu
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    #subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
