defaults:
  - _self_
  - callbacks: callbacks
  - private: default
  - datamodule: ljspeech
  - inference: basic
  - logging: wandb
  - loss: L1loss
  - metric: snr
  - model: diffwave_base
  - optimizer: adam
  - scheduler: linearwithwarmup
  - trainer: default_trainer
  - training: lj_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: test-run
  logs_folder_name: logs
  workspace: workspace-name
  project_name: project-name
  device: cpu
  log_code: False
  save_pytorch_model: True
  save_best: False
  convert_to_jit: True
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    #subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
