defaults:
  - _self_
  - preprocessing: spectrograms
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


general:
  run_name: preprocessing-run
  logs_folder_name: logs
  workspace: workspace-name
  project_name: project-name
  device: cpu
  log_code: False

hydra:
  run:
    dir: outputs/preprocessing_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/preprocessing_${now:%Y-%m-%d_%H-%M-%S}
    #subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
