datamodule_name: diffspeak.lightning_classes.datamodule.LJSpeechDataModule
path: ./data/tj/raw/LJSpeech-1.1/
params:
  unconditional: True
  batch_size: 8
  split: [0.9,0.05,0.05]
  num_workers: 4
  audio_len: 100000 # Lengths: min 24477, max:222621, mean:144952 median:149149 So I am not sure what to select here. 
  crop_mel_frames: 62 # Maybe not correct?
  pin_memory: True
  remove_shorts: True
  collator: diffspeak.datasets.collator.Collator

preprocessing:
  transformer: diffspeak.datasets.utils.Spectrogrammer
  subset_frac: 1
  sample_rate: 22050
  n_mels: 80
  n_fft: 1024
  hop_samples: 256
