datamodule_name: diffspeak.lightning_classes.datamodule.LJSpeechDataModule
path_to_metadata: ./data
params:
  datasets: ["tj", "nst_danish"]
  unconditional: False
  remove_shorts: True
  batch_size: 8
  split: [0.9,0.05,0.05]
  num_workers: 4
  audio_len: 16000
  crop_mel_frames: 62
  pin_memory: True
  collator: diffspeak.datasets.collator.Collator

preprocessing:
  transformer: diffspeak.datasets.utils.Preprocessor
  split_for_conditional_inference: [0.99, 0.01]
  subset_frac: 1
  sample_rate: 22050
  n_mels: 80
  n_fft: 1024
  hop_samples: 256
