
log: True
loggers:
  - class_name: pytorch_lightning.loggers.WandbLogger
    params:
      save_dir: ${general.logs_folder_name}
      #workspace: ${general.workspace}
      project: ${general.project_name}
      #api_key: ${private.wandb_api_key}
      name: ${general.run_name}
